swagger: "2.0"
info:
  version: "0.0.1"
  description: "REST API based on swagger (OPENAPI)"
  title: "API Arasaac"
# during dev, should point to your local machine
host: localhost:8000
# basePath prefixes all resource paths 
basePath: /api
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
  - text/html
paths:
  /keywords/:
    # our controller name
    x-swagger-router-controller: keywords
    get:
      operationId: getAll
      description: Obtain a list of keywords for pictogams for an specific language (es, en...)
      # define the type of response for Success "200" and Error
      parameters:
        - name: locale
          in: header
          description: Language of keyworks
          required: true
          type: string
          enum: [ "es", "en"]
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetKeywordsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /sessions:
    x-swagger-router-controller: sessions
    post:
      operationId: createSession
      description: Obtains a token for the user
      # define the type of response for Success "200" and Error
      parameters:
        - name: username
          in: formData
          description: User name for login
          required: true
          type: string
        - name: password
          in: formData
          description: User password 
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users:
    x-swagger-router-controller: users
    post:
      operationId: createUser
      description: Create a new user
      # define the type of response for Success "200" and Error
      parameters:
        - name: User
          in: body
          description: User data
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/{id}:
    x-swagger-router-controller: users
    get:
      operationId: getUser
      description: Obtain a list of keywords for pictogams for an specific language (es, en...)
      # define the type of response for Success "200" and Error
      parameters:
        - name: id
          in: path
          description: User id
          required: true
          type: integer
          format: int32
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetKeywordsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      operationId: updateUser
      description: Update user fields
      # define the type of response for Success "200" and Error
      parameters:
        - name: id
          in: path
          description: User id
          required: true
          type: integer
          format: int32
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetKeywordsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/activate/{url}:
    x-swagger-router-controller: users
    post:
      operationId: activateUser
      description: Create a new user
      # define the type of response for Success "200" and Error
      parameters:
        - name: url
          in: path
          description: Random generated key for user activation
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetKeywordsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  User:
    required:
      - name
      - email
      - username
      - password
    properties:
      name:
        type: string
      email:
        type: string
      username:
        type: string
      password:
        type: string
  GetKeywordsResponse:
    required:
      - keywords
    properties:
      keywords:
        type: string
  SuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string